export default {
  homeEmpty: require('../assets/icons/homeEmpty.png'),
  homeFilled: require('../assets/icons/homeFilled.png'),
  phoneEmpty: require('../assets/icons/phoneEmpty.png'),
  phoneFilled: require('../assets/icons/phoneFilled.png'),
  walletEmpty: require('../assets/icons/walletEmpty.png'),
  walletFilled: require('../assets/icons/walletFilled.png'),
  profile: require('../assets/icons/profile.png'),
  LiveChatsEmpty: require('../assets/icons/liveChatsEmpty.png'),
  LiveChatsFilled: require('../assets/icons/liveChatsFilled.png'),
  language: require('../assets/icons/Language.png'),
  home: require('../assets/icons/Home.png'),
  walletCircle: require('../assets/icons/WalletCircleIIcon.png'),
  SlotBooking: require('../assets/icons/SlotBooking.png'),
  CallHistory: require('../assets/icons/CallHistory.png'),
  ChatHistory: require('../assets/icons/ChatHistory.png'),
  TermsAndConditions: require('../assets/icons/TermsAndConditions.png'),
  Logout: require('../assets/icons/Logout.png'),
  yellowStar: require('../assets/icons/yellowStar.png'),
  dot3: require('../assets/icons/dot3.png'),
};
